import { FaJava, FaPython, FaNodeJs, FaDatabase } from "react-icons/fa";
import { SiTypescript, SiJavascript } from "react-icons/si";
import { DiJava } from "react-icons/di";
import { SiSpringboot } from "react-icons/si";

const projects = {
  personal: [
    {
      id: 2,
      title: "Cryptocurrency Exchange Application",
      date: "2025",
      description:
        "Handle user account, coin publication and fictitious stock price not so randomly generated by serverless functions.",
      image: "/projects/NFBAnk.png",
      technologies: ["TypeScript", "React", "Shadcn", "Firebase"],
      icon: <SiTypescript size={24} />,
      link: "https://nfb-ank-ef64d0.gitlab.io/",
      gitlab: "https://gitlab.com/projets-perso6401507/javascript/nfb-ank",
    },
    {
      id: 4,
      title: "Fast and robust E-commerce backend",
      date: "2024",
      description:
        "Complete Backend handling items, cart, products and customer, having authentication, tests, workers and a backoffice.",
      image: "/projects/Django.png",
      technologies: ["Python", "Django", "Docker", "SQLite"],
      icon: <FaPython size={24} />,
      gitlab: "https://gitlab.com/projets-perso6401507/python/tuto-storefront",
    },
    {
      id: 3,
      title: "Hammer Showcase Site",
      date: "2023",
      description:
        "Basic frameworkless ultra optimized HTML / CSS / JS website showcasing hammers.",
      image: "/projects/Martengo.png",
      technologies: ["JavaScript", "Plain HTML", "Plain CSS"],
      icon: <SiJavascript size={24} />,
      link: "https://martengo-899e88.gitlab.io",
      gitlab: "https://gitlab.com/projets-perso6401507/javascript/martengo",
    },
  ],
  academic: [
    {
      id: 6,
      title: "Job Application Platform",
      date: "2025",
      description:
        "Fully functional and robust job application platform with user authentication / authorization, analytics and a back-office.",
      image: "/projects/GrosBoulot.png",
      technologies: ["Node.js", "EJS", "Bootstrap", "MySQL"],
      icon: <FaNodeJs size={24} />,
    },
    {
      id: 7,
      title: "Parking lot Management System",
      date: "2024",
      description:
        "Python app running on a terminal allowing users to book places & get reductions according to their fidelity.",
      image: "/projects/Parking.png",
      technologies: ["Python", "PostgreSQL"],
      icon: <FaPython size={24} />,
      gitlab: "https://gitlab.com/projets-perso6401507/python/utc-parking",
    },
    {
      id: 9,
      title: "Household Task Management App",
      date: "2023",
      description:
        "Developed a mobile app to simplify household chore management in a fun and interactive way.",
      image: "/projects/ChoreUp.png",
      technologies: ["Java", "Android Studio", "Firebase"],
      icon: <FaJava size={24} />,
      link: "https://drive.google.com/file/d/1h9KPkzm5XkkomIvWdVtTxu4dWmyBzqzu/view",
    },
  ],
  professional: [
    {
      id: 10,
      title: "Secure Azure Storage Explorer",
      date: "2025",
      description:
        "AXA Solution to implement a secure storage explorer for Azure Blob Storage, allowing users to manage files and folders securely.",
      image: "/projects/WSSE.png",
      technologies: ["Spring Boot", "Bootstrap", "Azure"],
      icon: <SiSpringboot size={24} />,
    },
    {
      id: 11,
      title: "Advertising Campaign Manager",
      date: "2024",
      description:
        "Website to manage and create advertising campaigns with integrated AI.",
      image: "/projects/Alice.png",
      technologies: ["TypeScript", "React", "MongoDB", "Jenkins"],
      icon: <SiTypescript size={24} />,
    },
    {
      id: 12,
      title: "Postal Address Processing Software",
      date: "2023",
      description:
        "Ensure correct interoperability by analyzing physical addresses and converting them into coordinates.",
      image: "/projects/interoperabilite.png",
      technologies: ["Java"],
      icon: <DiJava size={24} />,
    },
    {
      id: 13,
      title: "Building Permit Database Interface",
      date: "2023",
      description:
        "Easy to manage and ship database interface for building permits.",
      image: "/projects/PermisConstruire.jpg",
      technologies: ["MySQL", "Java"],
      icon: <FaDatabase size={24} />,
    },
  ],
};

export default projects;
